// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlznok-Yy7a6t_8ovYx5w-Q8PXt99_FlE',
    appId: '1:487132405089:web:12f6397860222e2bb83920',
    messagingSenderId: '487132405089',
    projectId: 'my-application-10-d18d9',
    authDomain: 'my-application-10-d18d9.firebaseapp.com',
    databaseURL: 'https://my-application-10-d18d9-default-rtdb.firebaseio.com',
    storageBucket: 'my-application-10-d18d9.appspot.com',
    measurementId: 'G-KZGEBRR7YS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3jPt5ifj-KXLzkq1uQnEvLB1ds585tdg',
    appId: '1:487132405089:android:25da98b901b447c9b83920',
    messagingSenderId: '487132405089',
    projectId: 'my-application-10-d18d9',
    databaseURL: 'https://my-application-10-d18d9-default-rtdb.firebaseio.com',
    storageBucket: 'my-application-10-d18d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZEXWUp2pnYJ4d3KdX_lU_jBKDc6T9slw',
    appId: '1:487132405089:ios:9e0bdd7ea00067c8b83920',
    messagingSenderId: '487132405089',
    projectId: 'my-application-10-d18d9',
    databaseURL: 'https://my-application-10-d18d9-default-rtdb.firebaseio.com',
    storageBucket: 'my-application-10-d18d9.appspot.com',
    iosClientId: '487132405089-d91gbv6sifuc1a53oe6bdsajebuacdg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZEXWUp2pnYJ4d3KdX_lU_jBKDc6T9slw',
    appId: '1:487132405089:ios:9e0bdd7ea00067c8b83920',
    messagingSenderId: '487132405089',
    projectId: 'my-application-10-d18d9',
    databaseURL: 'https://my-application-10-d18d9-default-rtdb.firebaseio.com',
    storageBucket: 'my-application-10-d18d9.appspot.com',
    iosClientId: '487132405089-d91gbv6sifuc1a53oe6bdsajebuacdg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
